import FinanceComponents from "@/components/view/finance";

export const metadata = {
    title: "Tài chính",
    description: "Generated by create next app",
};

export default function OrdersPage(){
    return(
        <FinanceComponents/>
    )
}