import TeamManagerComponent from "@/components/manager/team";

export const metadata = {
    title: "Quản lý nhóm",
    description: "Generated by create next app",
};

export default function TeamManagerPage(){

    return(
        <TeamManagerComponent/>
    )
}