import LoginForm from "@/components/Login/LoginForm";
import {Suspense} from "react";

export const metadata = {
    title: "Login",
    description: "Generated by create next app",
};

export default function LoginPage(){
    return(
        <Suspense>
            <LoginForm/>
        </Suspense>
    )
}