import RefundComponents from "@/components/view/Refund&Return";

export const metadata = {
    title: "Refund & return",
    description: "Generated by create next app",
};

export default function RefundReturnPage(){
    return(
        <RefundComponents/>
    )
}