import TelegramManagerComponent from "@/components/manager/telegram/page";

export const metadata = {
    title: "Quản lý thông báo",
    description: "Generated by create next app",
};

export default function TelegramManagerPage(){

    return(
        <TelegramManagerComponent/>
    )
}