import NotificationManagerComponent from "@/components/manager/notification";

export const metadata = {
    title: "Quản lý webhooks",
    description: "Generated by create next app",
};

export default function NotificationManagerPage(){



    return(
        <NotificationManagerComponent/>
    )
}