import EmployeeManagerComponent from "@/components/manager/employee";

export const metadata = {
    title: "Quản lý nhân viên",
    description: "Generated by create next app",
};

export default function EmployeeManagerPage(){

    return(
        <EmployeeManagerComponent/>
    )
}