import OrderComponents from "@/components/view/Order/index,";

export const metadata = {
    title: "Đơn hàng",
    description: "Generated by create next app",
};


export default function OrdersPage(){
    return(
        <OrderComponents/>
    )
}