import ChangeProfilePage from "@/components/view/account/page";

export const metadata = {
    title: "Tài khoản",
    description: "Generated by create next app",
};

export default function OrdersPage(){
    return(
        <ChangeProfilePage/>
    )
}