
import ManagerLayout from "@/components/ManagerLayout";

export const metadata = {
  title: "Trang nhân viên",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
      <ManagerLayout>{children}</ManagerLayout>
  );
}
