


import AddInfoManagerComponent from "@/components/manager/addInfo";

export const metadata = {
    title: "Thông tin shop auth",
    description: "Generated by create next app",
};


export  default function AddInfoPage (){

    return <AddInfoManagerComponent/>
}