import ShopManagerComponent from "@/components/manager/shop";

export const metadata = {
    title: "Quản lý shop",
    description: "Generated by create next app",
};

export default function ShopManagerPage(){

    return(
        <ShopManagerComponent/>
    )
}